<?php
/**
 * 2FA / TOTP helper for Bradford Portal
 * 
 * To use: install TOTP library via Composer
 *   composer require sonata-project/google-authenticator
 * 
 * Or use a simpler solution like Spomky-Labs/otphp
 */

// require 'vendor/autoload.php';

/**
 * Generate a TOTP secret for a user
 * This secret is shared between the user's authenticator app and the server
 */
function generate_totp_secret()
{
    // Generate a random 32-character secret
    return bin2hex(random_bytes(16));
}

/**
 * Generate a QR code URL for Google Authenticator setup
 * User scans this with their phone to set up 2FA
 */
function get_totp_qr_code($email, $secret)
{
    // Format: otpauth://totp/Bradford Portal:email@example.com?secret=...&issuer=Bradford%20Portal
    $url = sprintf(
        'otpauth://totp/Bradford%%20Portal:%s?secret=%s&issuer=Bradford%%20Portal',
        urlencode($email),
        urlencode($secret)
    );
    
    // Use qr-server.com (free QR code service) instead of deprecated Google Charts
    $qrUrl = 'https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=' . urlencode($url);
    return $qrUrl;
}

/**
 * Verify a TOTP code entered by the user
 * This is where you'd use an authenticator library to validate the 6-digit code
 */
function hotp($secret, $counter)
{
    // convert secret from hex to binary
    $key = hex2bin($secret);
    // pack counter into 8-byte binary (big endian)
    $counterBytes = pack('N*', 0) . pack('N*', $counter);
    $hash = hash_hmac('sha1', $counterBytes, $key, true);
    $offset = ord(substr($hash, -1)) & 0x0F;
    $truncated = substr($hash, $offset, 4);
    $value = unpack('N', $truncated)[1] & 0x7FFFFFFF;
    return $value % 1000000;
}

/**
 * Verify a TOTP code entered by the user
 *
 * @param string $secret  hex string generated by generate_totp_secret()
 * @param string|int $code 6-digit code user entered
 * @param int $allowedWindow how many 30s steps before/after to allow
 * @return bool
 */
function verify_totp_code($secret, $code, $allowedWindow = 1)
{
    $timeStep = 30;
    $currentCounter = floor(time() / $timeStep);
    for ($i = -$allowedWindow; $i <= $allowedWindow; $i++) {
        $calc = hotp($secret, $currentCounter + $i);
        if (str_pad($calc, 6, '0', STR_PAD_LEFT) === strval($code)) {
            return true;
        }
    }
    return false;
}

?>
